# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from amalgam.communication.proto import message_pb2 as message__pb2


class ServerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHi = channel.unary_unary(
                '/ServerService/SayHi',
                request_serializer=message__pb2.RequestBody.SerializeToString,
                response_deserializer=message__pb2.Response.FromString,
                )
        self.PushData = channel.unary_unary(
                '/ServerService/PushData',
                request_serializer=message__pb2.RequestBody.SerializeToString,
                response_deserializer=message__pb2.Response.FromString,
                )


class ServerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHi': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHi,
                    request_deserializer=message__pb2.RequestBody.FromString,
                    response_serializer=message__pb2.Response.SerializeToString,
            ),
            'PushData': grpc.unary_unary_rpc_method_handler(
                    servicer.PushData,
                    request_deserializer=message__pb2.RequestBody.FromString,
                    response_serializer=message__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ServerService/SayHi',
            message__pb2.RequestBody.SerializeToString,
            message__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PushData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ServerService/PushData',
            message__pb2.RequestBody.SerializeToString,
            message__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
